"""Type stubs for descriptive_statistics module."""

from collections.abc import Sequence

def is_discrete(values: Sequence[float]) -> bool: ...
def is_continuous(values: Sequence[float]) -> bool: ...
def five_number_summary(values: Sequence[float]) -> dict[str, float]: ...
def median(values: Sequence[float]) -> float: ...
def interquartile_range(values: Sequence[float]) -> float: ...
def sample_variance(values: Sequence[float]) -> float: ...
def sample_std_dev(values: Sequence[float]) -> float: ...
def coefficient_of_variation(values: Sequence[float]) -> float: ...
def mean(values: Sequence[float]) -> float: ...
def draw_frequency_table(
    values: Sequence[str | int],
) -> dict[str | int, int]: ...
def draw_cumulative_frequency_table(values: Sequence[int]) -> dict[int, int]: ...
def detect_fake_statistics(
    survey_sponsor: str, is_voluntary: bool, correlation_not_causation: bool
) -> list[str]: ...
