"""Type stubs for hypothesis_testing module."""

def state_null_hypothesis(description: str) -> str: ...
def state_alternate_hypothesis(description: str) -> str: ...
def is_right_tailed(test_statistic: float, critical_value: float) -> bool: ...
def is_left_tailed(test_statistic: float, critical_value: float) -> bool: ...
def is_two_tailed(test_statistic: float, critical_value: float) -> bool: ...
def p_value_method(test_statistic: float, test_type: str = "two-tailed") -> float: ...
def reject_null(p_value: float, alpha: float) -> bool: ...
def t_score(
    sample_mean: float, population_mean: float, sample_std: float, n: int
) -> float: ...
def f_test(var1: float, var2: float) -> float: ...
def critical_value_z(alpha: float, test_type: str = "two-tailed") -> float: ...
def critical_value_t(alpha: float, df: int, test_type: str = "two-tailed") -> float: ...
def critical_value_f(alpha: float, dfn: int, dfd: int) -> float: ...
