"""Type stubs for linear_regression_utils module."""

from collections.abc import Sequence

def prepare_scatter_data(
    x: Sequence[float], y: Sequence[float]
) -> tuple[Sequence[float], Sequence[float]]: ...
def pearson_correlation(x: Sequence[float], y: Sequence[float]) -> float: ...
def coefficient_of_determination(x: Sequence[float], y: Sequence[float]) -> float: ...
def linear_regression(
    x: Sequence[float], y: Sequence[float]
) -> tuple[float, float, float, float, float]: ...
def regression_equation(x: float, slope: float, intercept: float) -> float: ...
def manual_slope_intercept(
    x: Sequence[float], y: Sequence[float]
) -> tuple[float, float]: ...
