name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'real_simple_stats/**'
      - '.github/workflows/docs.yml'

  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'real_simple_stats/**'

  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper versioning

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install -r docs/requirements.txt

    - name: Build documentation
      run: |
        cd docs
        make clean
        make html

    - name: Check documentation links
      run: |
        cd docs
        make linkcheck || true  # Don't fail on broken external links

    - name: Upload documentation artifact (for Pages)
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build/html/

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Configure Pages
      uses: actions/configure-pages@v5

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  # Deploy to ReadTheDocs webhook
  trigger-rtd:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Trigger ReadTheDocs build
      env:
        RTD_WEBHOOK_URL: ${{ secrets.RTD_WEBHOOK_URL }}
        RTD_WEBHOOK_TOKEN: ${{ secrets.RTD_WEBHOOK_TOKEN }}
      run: |
        if [ -n "$RTD_WEBHOOK_URL" ] && [ -n "$RTD_WEBHOOK_TOKEN" ]; then
          echo "Triggering ReadTheDocs build..."
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"ref": "main", "token": "'$RTD_WEBHOOK_TOKEN'"}' \
            "$RTD_WEBHOOK_URL"
          echo "ReadTheDocs build triggered successfully"
        else
          echo "ReadTheDocs webhook not configured - skipping"
        fi

  # (Optional) PR preview via Pages can be added later using environments
